extends Node
## Preloads all production scripts so the coverage fork instruments them at compile time.
## Harmless at runtime — preload() compiles without instantiating.

# missions
const MissionMarkerScript = preload("res://scenes/missions/mission_marker.gd")
const MissionMarkerManagerScript = preload("res://scenes/missions/mission_marker_manager.gd")

# pedestrians
const PedestrianScript = preload("res://scenes/pedestrians/pedestrian.gd")
const PedestrianModelScript = preload("res://scenes/pedestrians/pedestrian_model.gd")
const PedestrianRagdollScript = preload("res://scenes/pedestrians/pedestrian_ragdoll.gd")
const PedestrianFleeScript = preload("res://scenes/pedestrians/states/pedestrian_flee.gd")
const PedestrianIdleScript = preload("res://scenes/pedestrians/states/pedestrian_idle.gd")
const PedestrianWalkScript = preload("res://scenes/pedestrians/states/pedestrian_walk.gd")

# player
const PlayerScript = preload("res://scenes/player/player.gd")
const PlayerCameraScript = preload("res://scenes/player/player_camera.gd")
const PlayerFlashlightScript = preload("res://scenes/player/player_flashlight.gd")
const PlayerModelScript = preload("res://scenes/player/player_model.gd")
const PlayerWeaponScript = preload("res://scenes/player/player_weapon.gd")
const DrivingScript = preload("res://scenes/player/states/driving.gd")
const EnteringVehicleScript = preload("res://scenes/player/states/entering_vehicle.gd")
const ExitingVehicleScript = preload("res://scenes/player/states/exiting_vehicle.gd")
const PlayerIdleScript = preload("res://scenes/player/states/idle.gd")
const PlayerRunningScript = preload("res://scenes/player/states/running.gd")
const PlayerSwimmingScript = preload("res://scenes/player/states/swimming.gd")
const PlayerWalkingScript = preload("res://scenes/player/states/walking.gd")

# police
const PoliceOfficerScript = preload("res://scenes/police/police_officer.gd")

# ui
const GameHudScript = preload("res://scenes/ui/hud/game_hud.gd")
const InteractionPromptScript = preload("res://scenes/ui/hud/interaction_prompt.gd")
const MinimapHudScript = preload("res://scenes/ui/hud/minimap_hud.gd")
const StealProgressBarScript = preload("res://scenes/ui/hud/steal_progress_bar.gd")
const AudioPanelScript = preload("res://scenes/ui/menus/audio_panel.gd")
const ControlsPanelScript = preload("res://scenes/ui/menus/controls_panel.gd")
const PauseMenuScript = preload("res://scenes/ui/menus/pause_menu.gd")
const TouchControlsScript = preload("res://scenes/ui/touch_controls.gd")
const UiSoundsScript = preload("res://scenes/ui/ui_sounds.gd")

# vehicles
const BoatAudioScript2 = preload("res://scenes/vehicles/boat_audio.gd")
const BoatBodyBuilderScript = preload("res://scenes/vehicles/boat_body_builder.gd")
const BoatBodyInitScript = preload("res://scenes/vehicles/boat_body_init.gd")
const BoatControllerScript2 = preload("res://scenes/vehicles/boat_controller.gd")
const BoatWakeScript = preload("res://scenes/vehicles/boat_wake.gd")
const CarBodyBuilderScript = preload("res://scenes/vehicles/car_body_builder.gd")
const CarBodyInitScript = preload("res://scenes/vehicles/car_body_init.gd")
const CollisionCrimeDetectorScript = preload("res://scenes/vehicles/collision_crime_detector.gd")
const EngineAudioScript2 = preload("res://scenes/vehicles/engine_audio.gd")
const HelicopterScript = preload("res://scenes/vehicles/helicopter.gd")
const HelicopterAiScript = preload("res://scenes/vehicles/helicopter_ai.gd")
const HelicopterBodyBuilderScript = preload("res://scenes/vehicles/helicopter_body_builder.gd")
const HelicopterControllerScript = preload("res://scenes/vehicles/helicopter_controller.gd")
const NpcVehicleControllerScript = preload("res://scenes/vehicles/npc_vehicle_controller.gd")
const PoliceAiControllerScript = preload("res://scenes/vehicles/police_ai_controller.gd")
const PoliceLightBarScript = preload("res://scenes/vehicles/police_light_bar.gd")
const PoliceSirenScript = preload("res://scenes/vehicles/police_siren.gd")
const TireScreechAudioScript = preload("res://scenes/vehicles/tire_screech_audio.gd")
const VehicleCameraScript = preload("res://scenes/vehicles/vehicle_camera.gd")
const VehicleControllerScript = preload("res://scenes/vehicles/vehicle_controller.gd")
const VehicleHealthScript = preload("res://scenes/vehicles/vehicle_health.gd")
const VehicleLightsScript = preload("res://scenes/vehicles/vehicle_lights.gd")
const VehicleWaterDetectorScript = preload("res://scenes/vehicles/vehicle_water_detector.gd")

# world
const AmbientAudioScript = preload("res://scenes/world/ambient_audio.gd")
const BuildingDoorScript = preload("res://scenes/world/building_door.gd")
const CityScript = preload("res://scenes/world/city.gd")
const DayNightEnvironmentScript = preload("res://scenes/world/day_night_environment.gd")
const ChunkBuilderBridgeScript = preload("res://scenes/world/generator/chunk_builder_bridge.gd")
const CbBuildingsScript = preload("res://scenes/world/generator/chunk_builder_buildings.gd")
const ChunkBuilderFarmlandScript = preload("res://scenes/world/generator/chunk_builder_farmland.gd")
const ChunkBuilderHelipadScript = preload("res://scenes/world/generator/chunk_builder_helipad.gd")
const ChunkBuilderLightsScript = preload("res://scenes/world/generator/chunk_builder_lights.gd")
const ChunkBuilderMarkingsScript = preload("res://scenes/world/generator/chunk_builder_markings.gd")
const ChunkBuilderMountainScript = preload("res://scenes/world/generator/chunk_builder_mountain.gd")
const ChunkBuilderPiersScript = preload("res://scenes/world/generator/chunk_builder_piers.gd")
const ChunkBuilderRampsScript = preload("res://scenes/world/generator/chunk_builder_ramps.gd")
const ChunkBuilderRiverScript = preload("res://scenes/world/generator/chunk_builder_river.gd")
const ChunkBuilderRoadsScript = preload("res://scenes/world/generator/chunk_builder_roads.gd")
const CbRuralRoadsScript = preload("res://scenes/world/generator/chunk_builder_rural_roads.gd")
const CbRuralTreesScript = preload("res://scenes/world/generator/chunk_builder_rural_trees.gd")
const ChunkBuilderSuburbScript = preload("res://scenes/world/generator/chunk_builder_suburb.gd")
const ChunkBuilderTerrainScript = preload("res://scenes/world/generator/chunk_builder_terrain.gd")
const ChunkBuilderTreesScript = preload("res://scenes/world/generator/chunk_builder_trees.gd")
const ChunkBuilderVillagesScript = preload("res://scenes/world/generator/chunk_builder_villages.gd")
const PedestrianManagerScript = preload("res://scenes/world/pedestrian_manager.gd")
const PoliceManagerScript = preload("res://scenes/world/police_manager.gd")
const RadioSystemScript = preload("res://scenes/world/radio_system.gd")
const TrafficManagerScript = preload("res://scenes/world/traffic_manager.gd")
const WeaponPickupScript = preload("res://scenes/world/weapon_pickup.gd")

# src
const BiomeMapScript = preload("res://src/biome_map.gd")
const CharacterModelBaseScript = preload("res://src/character_model_base.gd")
const ChunkPersistenceScript = preload("res://src/chunk_persistence.gd")
const CityBoundaryScript = preload("res://src/city_boundary.gd")
const RiverMapScript = preload("res://src/river_map.gd")
const RoadGraphScript = preload("res://src/road_graph.gd")
const RoadGridScript2 = preload("res://src/road_grid.gd")
const PlayerStateScript = preload("res://src/state_machine/player_state.gd")
const StateScript = preload("res://src/state_machine/state.gd")
const StateMachineScript = preload("res://src/state_machine/state_machine.gd")
const TileCacheScript = preload("res://src/tile_cache.gd")
const TileProfileScript = preload("res://src/tile_profile.gd")
const TileResolverScript = preload("res://src/tile_resolver.gd")
const VehicleAiBaseScript = preload("res://src/vehicle_ai_base.gd")
const VehicleSpawnHelperScript = preload("res://src/vehicle_spawn_helper.gd")
const WeaponMeshBuilderScript = preload("res://src/weapon_mesh_builder.gd")
