extends Node
## Spawns and despawns NPC vehicles around the player to create traffic.
## Uses road_grid.gd for infinite tiling — spawns work at any world position.
## Applies random body variants (sedan, sports, SUV, hatchback, van, pickup).

const SPAWN_RADIUS := 120.0
const DESPAWN_RADIUS := 160.0
const DESPAWN_BEHIND_RADIUS := 70.0
const MIN_SPAWN_DIST := 60.0
const MIN_VEHICLE_DIST := 18.0
const SPAWN_INTERVAL := 1.0
const SPAWNS_PER_TICK := 2
const LOD_FREEZE_DIST := 140.0
const SEA_LEVEL := -2.0
# Max valid road height: terrain is capped at 6 m + 0.5 m ride clearance.
# Any vehicle above this after its spawn grace has failed to land and is culled.
const AIRBORNE_CULL_HEIGHT := 8.0
# Upward velocity thresholds for launch detection.
# During spawn grace (first 4 s): catch any spring impulse ≥ 8 m/s.
# After grace: normal driving over bumps can reach 10-20 m/s; only cull
# true explosions (freeze-unfreeze eject, physics blowup) at ≥ 40 m/s.
const LAUNCH_VEL_THRESHOLD := 8.0
const LAUNCH_VEL_POST_GRACE := 40.0

# Body variant definitions — name, spawn weight, and mass multiplier.
# Mesh shape is generated by car_body_builder.gd per variant.
const VARIANTS := [
	{"name": "sedan", "weight": 3, "mass_mult": 1.0},
	{"name": "sports", "weight": 2, "mass_mult": 0.9},
	{"name": "suv", "weight": 2, "mass_mult": 1.3},
	{"name": "hatchback", "weight": 2, "mass_mult": 0.85},
	{"name": "van", "weight": 1, "mass_mult": 1.6},
	{"name": "pickup", "weight": 1, "mass_mult": 1.5},
]
const HIGHWAY_INDICES := [0, 5]
const GLASS_COLOR := Color(0.6, 0.75, 0.85, 0.4)
const INTERIOR_COLOR := Color(0.12, 0.12, 0.12, 1)
# Adaptive spawn height: when a launch is detected, re-probe the terrain at
# that cell (50 m grid) and store a corrected Y for future spawns there.
# A 1 s retry gate prevents tight respawn loops; a FOV check delays the retry
# until the player is not looking directly at the spawn position.
const SPAWN_CELL := 50

const BoundaryScript = preload("res://src/city_boundary.gd")
var _grid = preload("res://src/road_grid.gd").new()
var _boundary = BoundaryScript.new()
var _biome_map: RefCounted  # fetched from city_manager meta
var _builder = preload("res://scenes/vehicles/car_body_builder.gd").new()
var _total_weight := 0
var _body_mesh_cache := {}  # variant_name -> ArrayMesh
var _window_mesh_cache := {}  # variant_name -> Dictionary of ArrayMesh
var _interior_mesh_cache := {}  # variant_name -> ArrayMesh
var _floor_mesh_cache := {}  # variant_name -> ArrayMesh
var _detail_mesh_cache := {}  # variant_name -> ArrayMesh
var _door_mesh_cache := {}  # variant_name -> Dictionary (meshes + pivots)

var _vehicles: Array[Node] = []
var _vehicle_scene: PackedScene = preload("res://scenes/vehicles/base_vehicle.tscn")
var _npc_controller_script: GDScript = preload("res://scenes/vehicles/npc_vehicle_controller.gd")
var _vehicle_health_script: GDScript = preload("res://scenes/vehicles/vehicle_health.gd")
var _vehicle_lights_script: GDScript = preload("res://scenes/vehicles/vehicle_lights.gd")
var _water_detector_script: GDScript = preload("res://scenes/vehicles/vehicle_water_detector.gd")
var _spawn_helper: GDScript = preload("res://src/vehicle_spawn_helper.gd")
var _spawn_timer := 0.0
var _launch_check_timer := 0.0
var _player: Node3D = null
var _rng := RandomNumberGenerator.new()
var _player_velocity := Vector3.ZERO
var _time_multiplier := 1.0
# Per-cell adaptive spawn height (Vector2i → float).
# Set when a launch-cull probes the real terrain at that grid cell.
var _cell_y: Dictionary = {}
# Per-cell retry gate (Vector2i → int ms). Spawn skipped until elapsed.
var _cell_retry_ms: Dictionary = {}

# Pre-cached materials (shared across all vehicles)
var _glass_mat: StandardMaterial3D
var _interior_mat: StandardMaterial3D
var _floor_mat: StandardMaterial3D
var _detail_mat: StandardMaterial3D
var _door_inner_mat: StandardMaterial3D
var _color_mats: Array[StandardMaterial3D] = []

var _car_colors: Array[Color] = [
	Color(0.15, 0.25, 0.55),
	Color(0.1, 0.5, 0.2),
	Color(0.9, 0.85, 0.7),
	Color(0.3, 0.3, 0.3),
	Color(0.85, 0.85, 0.85),
	Color(0.6, 0.1, 0.1),
	Color(0.95, 0.7, 0.1),
	Color(0.05, 0.05, 0.05),
	Color(0.95, 0.95, 0.95),
	Color(0.4, 0.2, 0.5),
]


func _ready() -> void:
	_rng.randomize()
	_boundary.init(_grid.get_grid_span(), _make_terrain_noise())
	_init_materials()
	EventBus.vehicle_entered.connect(_on_vehicle_stolen)
	EventBus.time_of_day_changed.connect(_on_time_changed)
	for v in VARIANTS:
		_total_weight += v.weight
		var vname: String = v.name
		_body_mesh_cache[vname] = _builder.build_body(vname)
		_window_mesh_cache[vname] = _builder.build_windows(vname)
		_interior_mesh_cache[vname] = _builder.build_interior(vname)
		_floor_mesh_cache[vname] = _builder.build_floor(vname)
		_detail_mesh_cache[vname] = _builder.build_details(vname)
		_door_mesh_cache[vname] = _builder.build_doors(vname)


func _init_materials() -> void:
	_glass_mat = StandardMaterial3D.new()
	_glass_mat.transparency = BaseMaterial3D.TRANSPARENCY_ALPHA
	_glass_mat.cull_mode = BaseMaterial3D.CULL_DISABLED
	_glass_mat.albedo_color = GLASS_COLOR

	_interior_mat = StandardMaterial3D.new()
	_interior_mat.albedo_color = INTERIOR_COLOR
	_interior_mat.cull_mode = BaseMaterial3D.CULL_DISABLED

	_floor_mat = StandardMaterial3D.new()
	_floor_mat.albedo_color = Color(0.15, 0.15, 0.15, 1.0)

	_detail_mat = StandardMaterial3D.new()
	_detail_mat.albedo_color = Color(0.15, 0.15, 0.15, 1.0)
	_detail_mat.cull_mode = BaseMaterial3D.CULL_DISABLED

	_door_inner_mat = StandardMaterial3D.new()
	_door_inner_mat.albedo_color = INTERIOR_COLOR

	for c in _car_colors:
		var mat := StandardMaterial3D.new()
		mat.albedo_color = c
		_color_mats.append(mat)


func _process(delta: float) -> void:
	if not _player:
		_player = get_tree().get_first_node_in_group("player") as Node3D
		if not _player:
			return

	var vehicle = _player.get("current_vehicle")
	if vehicle and vehicle is RigidBody3D:
		_player_velocity = (vehicle as RigidBody3D).linear_velocity
	elif "velocity" in _player:
		_player_velocity = _player.velocity
	else:
		_player_velocity = Vector3.ZERO

	# Launch detection: cull vehicles thrown upward by a bad spawn impulse or
	# freeze-unfreeze ejection.  Runs every 0.25 s rather than every frame —
	# the grace window is 0.5 s so 4 checks/s is more than sufficient.
	_launch_check_timer += delta
	if _launch_check_timer >= 0.25:
		_launch_check_timer = 0.0
		var launched: Array[Node] = []
		for v in _vehicles:
			if is_instance_valid(v) and "linear_velocity" in v:
				var vy: float = (v as RigidBody3D).linear_velocity.y
				var npc_v: Node = v.get_node_or_null("NPCVehicleController")
				var in_grace: bool = npc_v != null and npc_v._spawn_grace > 0.0
				var threshold: float = LAUNCH_VEL_THRESHOLD if in_grace else LAUNCH_VEL_POST_GRACE
				if vy > threshold:
					launched.append(v)
					var vpos: Vector3 = (v as Node3D).global_position
					# Probe the real terrain height at this cell so the next spawn
					# attempt uses a corrected Y instead of the flat-base-plane hit.
					var probe := (
						PhysicsRayQueryParameters3D
						. create(
							Vector3(vpos.x, 80.0, vpos.z),
							Vector3(vpos.x, -5.0, vpos.z),
						)
					)
					probe.collision_mask = 1
					var phit: Dictionary = _player.get_world_3d().direct_space_state.intersect_ray(
						probe
					)
					var corrected_y: float
					if not phit.is_empty():
						corrected_y = (phit["position"] as Vector3).y
					else:
						corrected_y = _boundary.get_ground_height(vpos.x, vpos.z)
					var cell := Vector2i(
						int(vpos.x) / SPAWN_CELL,
						int(vpos.z) / SPAWN_CELL,
					)
					_cell_y[cell] = corrected_y
					_cell_retry_ms[cell] = Time.get_ticks_msec() + 1000
		for v in launched:
			_vehicles.erase(v)
			if is_instance_valid(v):
				v.queue_free()

	_spawn_timer += delta
	if _spawn_timer >= SPAWN_INTERVAL:
		_spawn_timer = 0.0
		_despawn_far()
		for _i in range(SPAWNS_PER_TICK):
			_try_spawn()


func _try_spawn() -> void:
	if _rng.randf() > _time_multiplier:
		return

	var player_pos := _player.global_position
	var player_tile := (
		_grid
		. get_chunk_coord(
			Vector2(player_pos.x, player_pos.z),
		)
	)
	var player_biome := _get_biome(player_tile)
	var player_in_city := _is_road_grid_biome(player_biome)

	for _attempt in range(5):
		var is_ns := _rng.randi() % 2 == 0
		var road_idx: int
		if not player_in_city:
			road_idx = HIGHWAY_INDICES[_rng.randi() % HIGHWAY_INDICES.size()]
		else:
			road_idx = _rng.randi_range(0, _grid.GRID_SIZE)

		var road_center: float
		if is_ns:
			road_center = _grid.get_road_center_near(road_idx, player_pos.x)
		else:
			road_center = _grid.get_road_center_near(road_idx, player_pos.z)

		var rw := _grid.get_road_width(road_idx)
		var along := _rng.randf_range(-SPAWN_RADIUS, SPAWN_RADIUS)
		var spawn_pos: Vector3
		var direction: int
		var yaw: float

		if is_ns:
			var lane_offset := rw / 4.0
			var heading_north := _rng.randi() % 2 == 0
			if heading_north:
				direction = 0
				spawn_pos = Vector3(road_center + lane_offset, 0.5, player_pos.z + along)
				yaw = 0.0
			else:
				direction = 1
				spawn_pos = Vector3(road_center - lane_offset, 0.5, player_pos.z + along)
				yaw = PI
		else:
			var lane_offset := rw / 4.0
			var heading_east := _rng.randi() % 2 == 0
			if heading_east:
				direction = 2
				spawn_pos = Vector3(player_pos.x + along, 0.5, road_center + lane_offset)
				yaw = -PI / 2.0
			else:
				direction = 3
				spawn_pos = Vector3(player_pos.x + along, 0.5, road_center - lane_offset)
				yaw = PI / 2.0

		var dist := spawn_pos.distance_to(player_pos)
		if dist < MIN_SPAWN_DIST or dist > SPAWN_RADIUS:
			continue

		if _grid.is_on_ramp(spawn_pos.x, spawn_pos.z):
			continue

		var cell := Vector2i(int(spawn_pos.x) / SPAWN_CELL, int(spawn_pos.z) / SPAWN_CELL)
		# If this cell had a recent launch, respect the 1 s retry gate and
		# only proceed once the player is not facing the candidate position.
		if _cell_retry_ms.has(cell):
			if Time.get_ticks_msec() < _cell_retry_ms[cell]:
				continue
			if _is_in_player_fov(spawn_pos):
				continue
			_cell_retry_ms.erase(cell)

		var space: PhysicsDirectSpaceState3D = _player.get_world_3d().direct_space_state
		var probe: Dictionary = _spawn_helper.probe_spawn_surface(space, _boundary, spawn_pos)
		if not probe.ok:
			continue
		var surface_y: float = probe.surface_y
		var terrain_normal: Vector3 = probe.terrain_normal
		# If a previous launch-cull probed a corrected terrain height for this
		# cell, use it instead of the current surface_y.
		if _cell_y.has(cell):
			var probed: float = _cell_y[cell]
			if probed > surface_y:
				surface_y = probed
		spawn_pos.y = surface_y + 0.25

		var too_close := false
		for v in _vehicles:
			if (
				is_instance_valid(v)
				and spawn_pos.distance_to((v as Node3D).global_position) < MIN_VEHICLE_DIST
			):
				too_close = true
				break
		if not too_close:
			for v in get_tree().get_nodes_in_group("police_vehicle"):
				if spawn_pos.distance_to((v as Node3D).global_position) < MIN_VEHICLE_DIST:
					too_close = true
					break
		if too_close:
			continue

		# Never spawn in the player's forward hemisphere — cars must not
		# pop into view. Only allow spawns behind or to the sides.
		var h_vel := Vector3(_player_velocity.x, 0.0, _player_velocity.z)
		if h_vel.length_squared() > 1.0:
			var offset := spawn_pos - player_pos
			offset.y = 0.0
			if h_vel.normalized().dot(offset.normalized()) > 0.0:
				continue

		var vehicle := _vehicle_scene.instantiate()
		_apply_variant(vehicle)
		_randomize_color(vehicle)
		vehicle.position = spawn_pos
		_spawn_helper.apply_terrain_tilt(vehicle, terrain_normal, yaw)

		var vc := vehicle.get_node_or_null("VehicleController")
		if vc:
			vc.active = false

		var npc: Node = _npc_controller_script.new()
		npc.name = "NPCVehicleController"
		vehicle.add_child(npc)

		var vh: Node = _vehicle_health_script.new()
		vh.name = "VehicleHealth"
		vehicle.add_child(vh)

		get_tree().current_scene.add_child(vehicle)
		vehicle.add_to_group("npc_vehicle")

		var lights: Node3D = _vehicle_lights_script.new()
		lights.name = "VehicleLights"
		vehicle.get_node("Body").add_child(lights)
		lights.initialize(vehicle)

		npc.initialize(vehicle, road_idx, direction)

		var wd: Node = _water_detector_script.new()
		wd.name = "VehicleWaterDetector"
		vehicle.add_child(wd)

		_vehicles.append(vehicle)
		return


func _despawn_far() -> void:
	if not _player:
		return

	var player_pos := _player.global_position
	var h_vel := Vector3(_player_velocity.x, 0.0, _player_velocity.z)
	var moving := h_vel.length_squared() > 1.0
	var vel_dir := h_vel.normalized() if moving else Vector3.ZERO
	var to_remove: Array[Node] = []

	for v in _vehicles:
		if not is_instance_valid(v):
			to_remove.append(v)
			continue
		var v_pos := (v as Node3D).global_position
		# Cull vehicles stuck airborne after spawn grace (bad surface detection).
		var npc_ai_node: Node = v.get_node_or_null("NPCVehicleController")
		if npc_ai_node and npc_ai_node._spawn_grace <= 0.0 and v_pos.y > AIRBORNE_CULL_HEIGHT:
			to_remove.append(v)
			continue
		var d := v_pos.distance_to(player_pos)
		if d > DESPAWN_RADIUS:
			to_remove.append(v)
			continue  # skip LOD freeze for vehicles being despawned
		elif moving and d > DESPAWN_BEHIND_RADIUS:
			var offset := v_pos - player_pos
			offset.y = 0.0
			if vel_dir.dot(offset.normalized()) < -0.5:
				to_remove.append(v)
				continue  # skip LOD freeze for vehicles being despawned
		# Freeze/unfreeze GEVP physics by distance (skip during spawn grace)
		if is_instance_valid(v) and "freeze" in v:
			var npc_ai: Node = v.get_node_or_null("NPCVehicleController")
			if npc_ai and npc_ai._spawn_grace > 0.0:
				v.freeze = false
			else:
				var want_frozen: bool = d >= LOD_FREEZE_DIST
				if not want_frozen and (v as RigidBody3D).freeze:
					if _spawn_helper.is_embedded(v, get_tree().current_scene.get_world_3d()):
						to_remove.append(v)
						continue
				v.freeze = want_frozen

	for v in to_remove:
		_vehicles.erase(v)
		if is_instance_valid(v):
			v.queue_free()


func _on_vehicle_stolen(vehicle: Node) -> void:
	if vehicle in _vehicles:
		_vehicles.erase(vehicle)
		var npc := vehicle.get_node_or_null("NPCVehicleController")
		if npc:
			npc.deactivate()


func _pick_weighted_variant() -> int:
	var roll := _rng.randi_range(0, _total_weight - 1)
	var cumulative := 0
	for i in range(VARIANTS.size()):
		cumulative += VARIANTS[i].weight
		if roll < cumulative:
			return i
	return 0


func _apply_variant(vehicle: Node) -> void:
	var v: Dictionary = VARIANTS[_pick_weighted_variant()]
	var vname: String = v.name
	vehicle.set_meta("variant", vname)
	var body := vehicle.get_node_or_null("Body") as Node3D
	if not body:
		return

	# Assign cached body mesh
	var car_body := body.get_node_or_null("CarBody") as MeshInstance3D
	if car_body:
		car_body.mesh = _body_mesh_cache[vname]

	# Assign cached window meshes with shared glass material
	var windows: Dictionary = _window_mesh_cache[vname]
	for window_name in windows:
		var node := body.get_node_or_null(window_name) as MeshInstance3D
		if node:
			node.mesh = windows[window_name]
			node.material_override = _glass_mat
			node.transform = Transform3D.IDENTITY

	# Assign cached interior mesh
	var int_mesh: ArrayMesh = _interior_mesh_cache[vname]
	if int_mesh.get_surface_count() > 0 and car_body:
		var interior := MeshInstance3D.new()
		interior.name = "Interior"
		interior.mesh = int_mesh
		interior.material_override = _interior_mat
		car_body.add_child(interior)

	# Assign cached floor mesh
	var fl_mesh: ArrayMesh = _floor_mesh_cache[vname]
	if fl_mesh.get_surface_count() > 0 and car_body:
		var floor_node := MeshInstance3D.new()
		floor_node.name = "Floor"
		floor_node.mesh = fl_mesh
		floor_node.material_override = _floor_mat
		car_body.add_child(floor_node)

	# Assign cached detail mesh (grille, plates)
	var det_mesh: ArrayMesh = _detail_mesh_cache[vname]
	if det_mesh.get_surface_count() > 0 and car_body:
		var details := MeshInstance3D.new()
		details.name = "Details"
		details.mesh = det_mesh
		details.material_override = _detail_mat
		car_body.add_child(details)

	# Assign cached door meshes to pivots
	var door_data: Dictionary = _door_mesh_cache[vname]
	if door_data.size() > 0:
		_apply_door(
			body,
			"LeftDoorPivot",
			door_data,
			"LeftDoor",
			"LeftDoorInner",
			"LeftDoorWindow",
			"left_pivot",
			_door_inner_mat,
			_glass_mat,
		)
		_apply_door(
			body,
			"RightDoorPivot",
			door_data,
			"RightDoor",
			"RightDoorInner",
			"RightDoorWindow",
			"right_pivot",
			_door_inner_mat,
			_glass_mat,
		)

	# Adjust vehicle mass
	if "vehicle_mass" in vehicle:
		vehicle.vehicle_mass = 1200.0 * v.mass_mult


func _randomize_color(vehicle: Node) -> void:
	var body := vehicle.get_node_or_null("Body")
	if not body:
		return
	var car_body := body.get_node_or_null("CarBody") as MeshInstance3D
	if not car_body:
		return
	var mat: StandardMaterial3D = _color_mats[_rng.randi() % _color_mats.size()]
	car_body.material_override = mat
	# Apply same color to door meshes
	for pivot_name in ["LeftDoorPivot", "RightDoorPivot"]:
		var pivot := body.get_node_or_null(pivot_name)
		if pivot:
			for child in pivot.get_children():
				if child is MeshInstance3D and child.name.ends_with("Door"):
					child.material_override = mat


func _apply_door(
	body: Node3D,
	pivot_name: String,
	door_data: Dictionary,
	body_key: String,
	inner_key: String,
	window_key: String,
	pivot_key: String,
	inner_mat: StandardMaterial3D,
	glass_mat: StandardMaterial3D,
) -> void:
	var pivot := body.get_node_or_null(pivot_name) as Node3D
	if not pivot:
		pivot = Node3D.new()
		pivot.name = pivot_name
		body.add_child(pivot)
	pivot.position = door_data[pivot_key]
	var door_mi := MeshInstance3D.new()
	door_mi.name = body_key
	door_mi.mesh = door_data[body_key]
	pivot.add_child(door_mi)
	var inner_mi := MeshInstance3D.new()
	inner_mi.name = inner_key
	inner_mi.mesh = door_data[inner_key]
	inner_mi.material_override = inner_mat
	pivot.add_child(inner_mi)
	var win_mi := MeshInstance3D.new()
	win_mi.name = window_key
	win_mi.mesh = door_data[window_key]
	win_mi.material_override = glass_mat
	pivot.add_child(win_mi)


func _on_time_changed(hour: float) -> void:
	if hour < 5.0 or hour > 22.0:
		_time_multiplier = 0.5  # deep night
	elif hour < 7.0 or hour > 20.0:
		_time_multiplier = 0.7  # dawn/dusk
	else:
		_time_multiplier = 1.0  # day


func _fetch_biome_map() -> void:
	var cm := get_tree().get_first_node_in_group("city_manager")
	if cm and cm.has_meta("biome_map"):
		_biome_map = cm.get_meta("biome_map")


func _get_biome(tile: Vector2i) -> String:
	if _biome_map == null:
		_fetch_biome_map()
	if _biome_map:
		return _biome_map.get_biome(tile)
	# Fallback: use boundary
	if _boundary.is_city_tile(tile):
		return "residential"
	return "farmland"


## Returns true for biomes that use the road grid (city, residential, suburb).
static func _is_road_grid_biome(biome: String) -> bool:
	return biome in ["city_center", "residential", "suburb"]


## Returns true if spawn_pos falls within the player's forward ~120° FOV.
## Used to delay retries for launch-culled cells until the player looks away.
func _is_in_player_fov(spawn_pos: Vector3) -> bool:
	if not _player:
		return false
	var fwd: Vector3 = -_player.global_transform.basis.z
	var to_spawn: Vector3 = (spawn_pos - _player.global_position).normalized()
	return fwd.dot(to_spawn) > 0.5  # within ~60° each side of forward


## Creates a terrain noise matching city.gd _init_terrain_noise().
static func _make_terrain_noise() -> FastNoiseLite:
	return BoundaryScript.make_terrain_noise()
